import { Geist, Geist_Mono } from "next/font/google"
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.min.css'
import Script from 'next/script';

import "./globals.css"
import Menulateral from "./components/MenuLateral";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>


        <div className="container-fluid">
          <div className="row">
            <div className="col-3 menulateral" style={{ backgroundColor: "#061247" }} >
              {/* Logo dentro do menu lateral */}
              <div className="logo">
                <img src="https://placehold.co/50" alt="ImobConnect Logo" />
                <h1 className="fs-5 ImobConnect">ImobConnect</h1>
              </div>

              {/* Menu lateral */}
              <Menulateral />
              
            </div>

            <div className="col-9">
              {children}
            </div>
          </div>
        </div>


        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" />

      </body>
    </html>
  );
}
